version: "3"

services:
  app:
    container_name: ct-server
    environment:
      - PORT=3333
      - DB_URI=mongodb://mongo:27017/sky
      - NODE_ENV=dev
    restart: always
    build: .
    ports:
      - "3333:3333"
    links:
      - mongo
  mongo:
    container_name: ct-mongo
    image: mongo
    ports:
      - "27017:27017"
# version: "3"

# services:
#   server:
#     environment:
#       - PORT=9000
#       - DB_URI=mongodb://db:27017/sky
#       - NODE_ENV=dev
#     container_name: RESTApi-node
#     build: "."
#     volumes:
#       - ./:/app
#       - ./node_modules:/app/node_modules
#     environment:
#       NODE_ENV: dev
#     depends_on:
#       - db
#     links:
#       - db
#     ports:
#       - "9000:9000"

#   db:
#     image: "mongo"
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     volumes:
#       - ./data/db:/data/db
